### ISSUE TITLE
Capturing image upload date in the downloaded file name?

### ISSUE THREAD

**Issue by bialyrycerz** [mvabdi/vsco-scraper#25]
When downloading collections images (or perhaps other media), is it possible to set the downloaded file name to the date that the image was uploaded to VSCO?

**Comment by mvabdi** [comment]
I believe that for normal images it returns the epoch date for when it was uploaded, but I will have to go check.

**Comment by jeffkruczynski** [comment]
Some downloaded photos DO have the date in the exif data, presumably because the uploaded photo itself has it. But others do not have it in the exif data; however, the vsco page with the photo has a date. Is it possible to capture that date?
Some examples:
https://vsco.co/magalialmo/media/620b1626222e1537dd000001 has the exif date when downloaded
https://vsco.co/magalialmo/media/5a66d6591ac16a7485000001 does not have the exif date, but the vsco page shows a date of Jan 22, 2018.

**Comment by bialyrycerz** [comment]
Some downloaded photos DO have the date in the exif data, presumably because the uploaded photo itself has it. But others do not have it in the exif data; however, the vsco page with the photo has a date. Is it possible to capture that date?
Some examples:
https://vsco.co/magalialmo/media/620b1626222e1537dd000001 has the exif date when downloaded
https://vsco.co/magalialmo/media/5a66d6591ac16a7485000001 does not have the exif date, but the vsco page shows a date of Jan 22, 2018.

**Comment by parkerr82** [comment]
VSCO shows the date the image was uploaded and not the date the photo was taken. When the scraper downloads the image, the file name is the upload date represented as a Unix timestamp. VSCO ignores the exif data (regardless of whether it exists). 

Here's a handy tool to convert a Unix timestamp to a more human-readable format:

https://www.epochconverter.com

So to the original question, the scraper already does this.

**Comment by bialyrycerz** [comment]
Ahhh...thank you! I had not realized the file name is the timestamp. I had just assumed it was an index number. Super helpful -- thank you!
